"""Added order records

Revision ID: 86f96539fd83
Revises: 1da07da1e9d6
Create Date: 2020-03-31 16:46:20.887397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f96539fd83'
down_revision = '1da07da1e9d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_order',
    sa.Column('order_hash', sa.String(length=66), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=True),
    sa.Column('event_idx', sa.Integer(), nullable=True),
    sa.Column('base', sa.String(length=66), nullable=False),
    sa.Column('quote', sa.String(length=66), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('otype', sa.SmallInteger(), nullable=False),
    sa.Column('price', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('buy_amount', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('sell_amount', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.PrimaryKeyConstraint('order_hash')
    )
    op.create_index('ix_data_order_block_id_base_quote', 'data_order', ['block_id', 'base', 'quote'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_data_order_block_id_base_quote', table_name='data_order')
    op.drop_table('data_order')
    # ### end Alembic commands ###
